### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by SkrytnayaRediska** [ZenyaBelkov/Homework_lesson_10#1]
https://github.com/ZenyaBelkov/Homework_lesson_10/blob/e284636c71426135b9869cdf8f01e163d1a7e554/venv/oop.py#L197

self is a reference to an object. it is a bit strange to compare it to a string value

**Comment by ZenyaBelkov** [comment]
Fixed in a new brunch https://github.com/ZenyaBelkov/Homework_lesson_10/blob/1-solution/venv/oop.py
